### ISSUE TITLE
Add importable utility functions for identifiers retrieval

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit-js#10]
Things such as smiles variants, inchikey, molblocks and more

**Comment by thegodone** [comment]
would be nice to have PLAIN Smiles available aka: MolToSmiles( isomericSmiles = False)

**Comment by MichelML** [comment]
Hi @thegodone, thanks for the request and interest in the project, can you log this as a feature request so we can track it and assign it to a potential contributor down the road. Also, it would help in slowly building an active community around this initiative.

Here's a starter link for you: https://github.com/MichelML/rdkit-js/issues/new?assignees=&labels=&template=feature_request.md&title=

If you're too busy and don't do it by the end of the week, no worries I'll log it myself :pray:
