### ISSUE TITLE
Expose highlightAtomColors and highlightBondColors as in the python package

### ISSUE THREAD

**Issue by ben-ikt** [rdkit/rdkit-js#212]
In the python package, I can generate an image with different colors for the highlighted atoms, but I can't via RDKit.js.

Example in python [DrawMolecule api](https://www.rdkit.org/docs/source/rdkit.Chem.Draw.rdMolDraw2D.html):

```python
drawer.DrawMolecule(
        mol,
        highlightAtoms=[0,1],
        highlightBonds=[1,2],
        highlightAtomColors=[rgb1, rgb2],
        highlightBondColors=[rgb3, rgb4],
)
```

With RDKit.js I have only the highlightColour option.
[RDKit.js options](https://www.rdkitjs.com/#drawing-molecules-all-options)

```javascript
 mol = this.get_molecule(smiles);
const svg = mol.get_svg_with_highlights(JSON.stringify({
        atoms: [0, 1],
        bonds: [1,2]
        highlightColour: [rgb]
}));
```

It would be great if I could have the same interface as python :

```javascript
const svg = mol.get_svg_with_highlights(JSON.stringify({
        atoms: [0, 1],
        bonds: [1,2],
        highlightAtomColors=[rgb1, rgb2],
        highlightBondColors=[rgb3, rgb4],
}));
```

**Comment by MichelML** [comment]
@ptosco @greglandrum should this be transferred to the main rdkit repo?

**Comment by ptosco** [comment]
@MichelML You don't need to bother. I'll see if I can add that tomorrow to MinimalLib so it can make the 2022.09 release - it's a simple change.

**Comment by MichelML** [comment]
closing as merged in main rdkit repo, thank you @ptosco
