### ISSUE TITLE
RuntimeError: Aborted(OOM). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by ashipiling** [rdkit/rdkit-js#287]
When I draw more than 200 molecules in one page, the page reports OOM error.

Method: load the javascript file and instantiate the wasm module inside the head tag of index.html

Version: 2022.09.1

Browser: Edge

![image](https://user-images.githubusercontent.com/44961008/206121876-29d0355b-7be7-41be-817e-8c2d0e446bf6.png)

**Comment by ptosco** [comment]
This is not a bug. You most likely ran OOM because every time you instantiate a molecule, you need to explicitly delete it calling its `delete()` method, otherwise you'll be leaking memory.
```javascript
mol = rdkitModule.get_mol('CCC');
// do something with your mol
// when done, delete it
mol.delete();
```

**Comment by ashipiling** [comment]
thanks!
