### ISSUE TITLE
Angular examples website build and deployment are failing

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit-js#332]
@Phil-DS do you think you could have a look at this? It fails because of the following errors:

```


Expand 37 Lines
--
08:44:50.225 | ./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
08:44:50.225 | Error: Found non-callable @@iterator
08:44:50.225 |  
08:44:50.225 | ./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
08:44:50.225 | Error: Found non-callable @@iterator

```  

Build reference: https://vercel.com/invivoai-platform/rdkitjs-angular-website/AoCKbh5aeBJyc6a2zKLeBCbEwM8w  

--------------------------------  

It may be because of some dependencies update I did recently, but I'd like to have your take on it first and see if you could debug this quickly.

**Comment by MichelML** [comment]
@Phil-DS can you make a PR to update the package.json of your angular example to the previous dependencies? I'll make sure to update the vercel build to build the angular website in isolation of the other websites and dependencies.

Does that make sense?

**Comment by Phil-DS** [comment]
> @Phil-DS thanks for the investigation. Do you think you could make a PR to update the package.json of your angular example to the previous dependencies? I'll make sure to update the vercel build to build the angular website in isolation of the other websites and dependencies on my end once this is done.
> 
> Does that make sense?

Makes sense. PR is now up
