### ISSUE TITLE
Q1 2023 release broke some examples

### ISSUE THREAD

**Issue by adam-of-barot** [rdkit/rdkit-js#334]
**Describe the bug**
The Q1 2023 release (v2023.3.1) changed some JS methods to take a single JSON string as a parameter instead of multiple individual parameters. This results in some examples (like the one using generate_aligned_coords) to error out.

**To Reproduce**
1. Go to https://www.rdkitjs.com/#drawing-molecules-constraints
2. Click on 'Run'
3. Open the Developer Console
4. Observer the error (Uncaught 1206664)

**Expected behavior**
The code does not throw an uncaught error.

**Desktop**
 - OS: [Linux Mint 20.3 Cinnamon]
 - Browser [Firefox]
 - Version [v2023.3.1-1.0.0]

**Note**
The typescript docs will also need to be updated.

**Comment by MichelML** [comment]
changes are here, I'll fix this https://github.com/rdkit/rdkit/compare/Release_2022_09_5...Release_2023_03_1#diff-389cc8f46359a91ef65f3ffc78609da315b6f0ffed9bbdcd8fd3b7ab12df6a3b

**Comment by adam-of-barot** [comment]
The mentioned example seems to work fine now, so I'll go ahead and close this.
