### ISSUE TITLE
Cannot Generate Molecule From MolFile - No Examples?

### ISSUE THREAD

**Issue by Eelesy** [rdkit/rdkit-js#357]
Hi,

I can generate molecules using 'get_mol()' and SMILES quite easily.

I have a need to generate via MolFiles or MolBlocks - the documentation says it takes them in as an input but I am tearing my hair out trying to get one to work?

I have the files stored locally, I assume a file path is not right? I have used a http client in Angualr to load the content of the file as a string and pass that, no luck. I have also just created the contents of the mol file as a var and passed that in and that does not work.

Has anyone had any joy with MolFiles?

**Comment by ptosco** [comment]
This is not an issue - could  you please ask this question in the Discussions tab so it is more easily searchable? Thank you.
