### ISSUE TITLE
NextJS Server-side App Router Compatibility

### ISSUE THREAD

**Issue by sgoodrow-zymergen** [rdkit/rdkit-js#359]
**Is your feature request related to a problem? Please describe.**
I am trying to use this package to render molecule images in a NextJS application.

I have been able to do this successfully in the client by loading the unpkg source in a script tag and using the window object, however I'd like to be able to use the package from the server so that I can avoid shipping it to the browser and include it in my node modules as a direct dependency.

I have been able to do this using the example, however the example is slightly simplified and only loads images on the home page.

When I try to load images on multiple different routes, the initRDkitModule function looks for the wasm bundle in the same relative location. This means the next.config.js webpack configuration needs to copy the wasm bundle into each route.

**Describe the solution you'd like**
I am fairly new to NextJS and using wasm, so I don't have a suggestion for a solution, but it's fairly easy to reproduce the problem by adding a page route to the example app and trying to use the molecule component from there.

NextJS will search in `chunks/app/<page>` for the bundle instead of `chunks/app`.

I was able to get around this by putting it on an api route, but now the client has to make HTTP requests for each image, which won't scale well (browser limits number of in-flight requests and this adds a lot of additional round trips).

I am using the new NextJS app router, if that's relevant.

**Comment by ptosco** [comment]
This is not a bug report, so would you mind asking this question in the Discussions tab? Thus it will be more easily searchable by others. Thanks!
