### ISSUE TITLE
.d.ts (type definition files) for optimal Typescript usage

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit-js#36]

**Comment by adam-of-barot** [comment]
Hello!

I have a couple of basic questions:

- Are the function/class declarations needed for this located in the .h and .cpp files over at the MinimalLib repo?
- Should the .d.ts file live in the project root?

**Comment by MichelML** [comment]
Hi @adam-of-barot 

> Are the function/class declarations needed for this located in the .h and .cpp files over at the MinimalLib repo?
The class and functions in https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/jswrapper.cpp should have related types imho. I haven't dig into how easy it will be to do this in a wasm context like rdkit-js however.

>  Should the .d.ts file live in the project root?
the .d.ts files should be generated under the `dist` folder during the build and specified in the package.json here https://github.com/rdkit/rdkit-js/blob/master/package.json#L48

cc @ptosco

**Comment by adam-of-barot** [comment]
I'm unfortunately not very well versed with C++, much less WASM, so all I could manage was define things manually.
But auto-generation sounds way better.

**Comment by MichelML** [comment]
@adam-of-barot it's definitely a good start, and could turn out to be the better way, time will tell :+1:
