### ISSUE TITLE
React Example bug

### ISSUE THREAD

**Issue by kulmes** [rdkit/rdkit-js#361]
**Describe the bug**
In the react example, the sub-structure search portion seems to crash or have some issue when an invalid SMILES/SMARTS string is provided.

**To Reproduce**
1. Load the React example
2. Go to sub-structure search and type an invalid SMILES string (I use "P=")
3. You can see just "P" works to find molecules with phosphorus, but when you type in = the section disappears.  If you are fast enough and can get in "P=S" before the "P=" search is complete that seems to execute properly.

**Expected behavior**
Like the Vue and Angular examples an invalid SMILES/SMARTS string should do nothing and leave the last valid search intact.  This allows you to type in and edit SMILES strings and see how the search results change (e.g. I don't think going to a blank set or back to all the molecules would work well)

**Screenshots**
Can't really screen shot the absence of a section

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome and edge

**Smartphone (please complete the following information):**
N/A

**Additional context**
I'm just learning javascript/react so take the following with a grain of salt, but trying to track this down it seems to be an issue with the handle search change function ... specifically the line that sets the query mol ("const qmol = window.RDKit.get_qmol(currentVal);"  get_qmol seems to return null if provided an invalid SMILES/SMARTS string.  I think the error happens when qmol is then used a few lines later.  The errors I"ve seen also happen where we do a qmol.delete(), however that happens 40 times, which makes me think that perhaps it's an issue in the render() function where we're selecting the first 40 matches ...

**Comment by kulmes** [comment]
ok, tracking this down more I think it's related to this recent change:
https://github.com/rdkit/rdkit-js/discussions/336
non-valid input to a mol generating function no longer returns a valid mol object that you can do stuff with like call .delete or call .is_valid on

**Comment by MichelML** [comment]
thank you @kulmes !
